apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: "{{ .Values.NAMESPACE }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-set-headers: |
      X-Forwarded-Host $host;
      X-Forwarded-Proto $scheme;
      X-Forwarded-For $proxy_add_x_forwarded_for;
      Upgrade $http_upgrade;
      Connection "Upgrade";  
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.org/client-max-body-size: "10g"
    nginx.org/websocket-services: nextcloud-aio-apache
    cert-manager.io/cluster-issuer: letsencrypt-dns-luis
    cert-manager.io/issue-temporary-certificate: "false"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  {{- range .Values.ingress.hosts }}
  {{- $name := split "." .host }}
    - hosts:
        - {{ .host }}
      secretName: letsencrypt-{{ $name._1 }}-prod
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-aio-apache
                port:
                  number: {{ $.Values.APACHE_PORT }}
  {{- end }}